services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment-splitter-db
    volumes:
      - payment_splitter_db:/var/lib/postgresql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mailcatcher:
    image: 'sj26/mailcatcher'
    ports:
      - '1025:1025'
      - '1080:1080'

volumes:
  payment_splitter_db:
